config/routes.rb
Rails.application.routes.draw do
  resources :adventures, only: [:index, :show, :new, :create, :edit, :destroy]
  resources :explorers, only: [:index, :new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  root :to => "explorers#new"

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  belongs_to :explorer
end

app/models/explorer.rb
require 'bcrypt'
class Explorer < ActiveRecord::Base
  has_secure_password
  has_many :adventures
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  def index
     if params[:explorer_id] != nil
      @adventures = Adventure.where(explorer_id: params[:explorer_id])
     else
       @adventures = Adventure.all
     end
  end

  def new
    @adventure = Adventure.new
  end

  def create
    if current_explorer != nil
      adventure = Adventure.new(params.require(:adventure).permit(:destination, :duration, :price))
      adventure.explorer_id = current_explorer.id
      if adventure.save
        redirect_to adventures_path(explorer_id: current_explorer.id)
      else
        redirect_to new_adventure_path
      end
    end
  end

  def edit
  end


  def destroy
    @adventure = Adventure.find(params[:id])
    @adventure.delete
    redirect_to adventures_path
  end


  def show
    @adventure = Adventure.offset(rand(Adventure.count)).first


  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_explorer
  def current_explorer
    @current_explorer = Explorer.where(id: session['explorer_id']).first
  end
end

app/controllers/explorers_controller.rb
class ExplorersController < ApplicationController
    def index
      @explorer = Explorer.all
    end

    def new
      @explorer = Explorer.new
    end

    def create
      explorer = Explorer.new(params.require(:explorer).permit(:email, :exp_name, :password, :password_confirmation,))
      if explorer.save
        session["explorer_id"] = explorer.id.to_s
        redirect_to new_adventure_path
      else
        redirect_to new_explorer_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @explorer = Explorer.new
  end

  def create
    e = Explorer.where(email: params[:explorer][:email]).first
    if e != nil && e.authenticate(params[:explorer][:password])
      session['explorer_id'] = e.id.to_s
      @current_explorer = Explorer.find(session['explorer_id'])
      redirect_to new_adventure_path(explorer_id: e.id)
    else
      redirect_to new_sessions_path
    end
  end

  def destroy
    session.destroy
    redirect_to new_sessions_path
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/explorers_helper.rb
module ExplorersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/adventures/destroy.html.erb
<h1>Adventures#destroy</h1>
<p>Find me in app/views/adventures/destroy.html.erb</p>

app/views/adventures/edit.html.erb
<h1>Adventures#edit</h1>
<p>Find me in app/views/adventures/edit.html.erb</p>

app/views/adventures/index.html.erb
<div class="row center-text">
  <div class="small-6 small-centered columns ">
    <h2> There is still so much to do</h2>
<% @adventures.each do |a| %>
    <%= a.destination %><br />
    <%= link_to 'Destroy', a , method: :delete %>
    <hr />
<% end %>
    </div>
    </div>

app/views/adventures/new.html.erb
<div class="row center-text">
<%= form_for @adventure, :html => {:class => 'custom'} do |f| %>
    <div class="small-6 small-centered columns ">
    <br/>
     <%= f.label 'Destination' %>
      <%= f.text_field :destination %><hr>
      <%= f.check_box :is_outside %>
      <%= f.label 'Outdoors' %><br />
      <%= f.check_box :is_aquatic %>
      <%= f.label 'Aquatic' %><br />
      <%= f.check_box :is_sturdy_shoes %>
      <%= f.label 'Wear Sturdy Shoes' %><br />
      <%= f.check_box :is_inside %>
      <%= f.label 'Inside' %><br />
      <%= f.check_box :is_artful %>
      <%= f.label 'Culturally Stimulating' %><br />
      <%= f.check_box :is_full_day %>
      <%= f.label 'Is this a full day excursion?' %><br />

      <%= f.submit 'Create Adventure', :class => 'button success' %>
<% end %>

</div>
</div>

app/views/adventures/show.html.erb
<div class="row center-text">
  <div class="small-8 medium-centered columns ">
<br/>
    <br/>
    <h1 class="text-center"><%= @adventure.destination %> </h1>
    <% if @adventure.is_outside == true%>
    <%= image_tag 'compass.png' %>
      <% end %>
      </div>
    </div>

app/views/explorers/_form.html.erb
<%= form_for @explorer do |f| %>
 Email:                    <%= f.text_field :email %><br />
    Password:              <%= f.password_field :password %><br />
    Password Confirmation: <%= f.password_field :password_confirmation %><br />
    <%= f.submit 'Embark With Us', :class => 'button success' %>
<% end %>

app/views/explorers/new.html.erb
<div class="row center-text">
  <div class="small-6 small-centered columns ">
    <br/>
    <br/>
<%= render partial: "form" %>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title> "Here Be Monsters" </title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <% if current_explorer != nil %>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= @current_explorer %> </h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <% if current_explorer != nil %>
      <ul class="right">
        <li class="active"><%=link_to "EMBARK!", adventure_path(session['explorer_id']) %></li>
       <% else %>
            <li>Get Out There</li>
          <% end %>
        <li class="has-dropdown">
          <a href="#">Manage Provisions</a>
          <ul class="dropdown">

            <li class="active"><%= link_to "Create Adventure",new_adventure_path(session['explorer_id']) %></li>
            <li class="active"><%= link_to "Edit Adventures", adventures_path(session['explorer_id']) %></li>
          </ul>
        </li>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li>
          <% if current_explorer != nil %>
              <%= link_to "Log Out", sessions_path, method: :delete %>

          <% else %>
              <%= link_to "Sign Up", new_explorer_path %></li>
          <% end %>
              </ul>
    </section>
  </nav>
     <% else %>
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "Log In", new_sessions_path %></h1>
            </ul>
          </nav>

      <% end %>

    <%= yield %>


  </body>
</html>